name: Deploy
on:
  push:
    branches:
      - main
jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: version
        uses: salsify/action-detect-and-tag-new-version@v2
  npm-package:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn --immutable
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
